/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DAOMultiSigWallet } from "./DAOMultiSigWallet.sol/DAOMultiSigWallet";
export type { GasOptimizer } from "./GasOptimizer.sol/GasOptimizer";