/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  GasOptimizer,
  GasOptimizerInterface,
} from "../../contracts/GasOptimizer";

const _abi = [
  {
    inputs: [],
    name: "ArrayLengthMismatch",
    type: "error",
  },
  {
    inputs: [],
    name: "DivisionByZero",
    type: "error",
  },
  {
    inputs: [],
    name: "DuplicateAddress",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidChunkSize",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidSignatureLength",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidSignatureRecoveryId",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidUrgencyMultiplier",
    type: "error",
  },
] as const;

const _bytecode =
  "0x602d6050600b82828239805160001a6073146043577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea164736f6c6343000814000a";

type GasOptimizerConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: GasOptimizerConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class GasOptimizer__factory extends ContractFactory {
  constructor(...args: GasOptimizerConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      GasOptimizer & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): GasOptimizer__factory {
    return super.connect(runner) as GasOptimizer__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): GasOptimizerInterface {
    return new Interface(_abi) as GasOptimizerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): GasOptimizer {
    return new Contract(address, _abi, runner) as unknown as GasOptimizer;
  }
}
