/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { DAOMultiSigWallet__factory } from "./DAOMultiSigWallet.sol/DAOMultiSigWallet__factory";
export { GasOptimizer__factory } from "./GasOptimizer.sol/GasOptimizer__factory";