/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type * as contracts from "./contracts";
export * as factories from "./factories";
export { DAOMultiSigWallet__factory } from "./factories/contracts/DAOMultiSigWallet.sol/DAOMultiSigWallet__factory";
export { GasOptimizer__factory } from "./factories/contracts/GasOptimizer.sol/GasOptimizer__factory";
export type { DAOMultiSigWallet } from "./contracts/DAOMultiSigWallet.sol/DAOMultiSigWallet";
export type { GasOptimizer } from "./contracts/GasOptimizer.sol/GasOptimizer";